### ISSUE TITLE
2FAS Android can retry password again and again

### ISSUE THREAD

**Issue by huapage** [twofas/2fas-android#1]
Install 2FAS Android in a new phone. Enable Cloud sync. If the backup has password enabled, 2FAS will ask for password. Input some wrong password, the application allow the user to try again and again.

Correct behaviour is after 3 or 5 times of fail, 2FAS should delay retry for some time since possible an attack is on going.

**Comment by 2fas-com** [comment]
Thank you, you're right! we'll fix that asap!

**Comment by 2fas-com** [comment]
Ok, so we've just consulted it with our safety officer and the bottom line is that we can add this solution, but it only will affect UI actions. If someone really would like to brute force this password, it can (sadly) be done outside our app, and in that case, we have no control over it.

**Comment by huapage** [comment]
To prevent this one: "If someone really would like to brute force this password, it can (sadly) be done outside our app".
We can choose a strong password ( e.g. length > 14 characters ) to make it difficult to brute force the password.
