### ISSUE TITLE
Feature request: add AppConfig for MDM

### ISSUE THREAD

**Issue by xvsun** [twofas/2fas-android#10]
Mobile device management (MDM) is using AppConfig standard to preset and configure settings so apps can be mass deployed to devices: [https://www.appconfig.org](https://www.appconfig.org).

I think these options should be available:
- option that passcode is required
- toggle/hide Backup functionality 
- toggle/hide biometric option
- preset lockout settings
- toggle/hide browser extension

**Comment by 2fas-com** [comment]
Thank you for that suggestion - we've decided to implement this (both for Android and iOS). However, no ETA on this.
