### ISSUE TITLE
Automatic local backups to custom folder

### ISSUE THREAD

**Issue by timkgh** [twofas/2fas-android#104]
If we don't want backups to Google Drive, we should be able to back up to a custom local folder automatically, the app should remember the backup password and it should retain a certain number of backups. See Aegis for the options the app provides. Then the backups can be sync'ed elsewhere via Syncthing, FolderSync, etc.

I know there is export, but that is a tedious manual process when you have to enter (strong) passwords twice. It needs to be automated, when an entries change for example.

**Comment by 2fas-com** [comment]
We understand, but unfortunately we do not plan to implement this. We may consider it in the future.
