### ISSUE TITLE
Why is there no other option than Google Drive?

### ISSUE THREAD

**Issue by seriousfreezing** [twofas/2fas-android#108]
Why is there no option to use Proton Drive, for example?

**Comment by 2fas-com** [comment]
In short, we use secure space in Google Drive for Android apps, and there is no direct access to this space from the Google Drive level, which is a secure approach. Similarly, on iOS, we only use iCloud because it provides additional security options.

**Comment by seriousfreezing** [comment]
Okay, fine. But I still think it would be interesting to be able to use other services, for example: If I don't like Google, I could use Proton Drive or something like that
