### ISSUE TITLE
Allow spaces in export password

### ISSUE THREAD

**Issue by Lordmau5** [twofas/2fas-android#11]
Hey everyone!
In the process of switching away from Authy where I can and onto 2FAS because so far it looks pretty solid.
Clean design, cool "next token" functionality, backup to GDrive (and also into a password-protected file)

I wanted to test export my vault just now with a password that contains spaces (rather, a passphrase)
However, it threw an error that spaces aren't supported.
Upon checking the code, it seems to not be included in the regex here:
https://github.com/twofas/2fas-android/blob/6550107eb5e2c568211957ac34a83854fe68d345/backup/src/main/java/com/twofasapp/backup/ui/export/ExportBackupPasswordDialog.kt#L93

Is this a limitation in your encryption code or simply something that you guys didn't consider when writing that regex?

Thought I'd open an issue about this since I didn't see another one yet :)

On another note, thank you for such a great app! Already liking it!

**Comment by rafakob** [comment]
Hey! We're glad that you like our app :)

As for the "spaces" in passwords. They could be used for encryption but white characters can be tricky and may sometimes confuse users. Imagine adding unwanted space at the end of your password which was added there by a miss click or by some keyboard autocorrect. We had such cases in the past and that's why we decided to disable them.
What I can suggest is replacing "space" with some other special character like hyphen.

**Comment by Lordmau5** [comment]
Ah I see, yeah I can understand that as being an issue.

However, that sparks the question on whether adding a settings toggle for allowing spaces in passwords would be an idea.

With spaces I know that I will definitely have spaces in the passwords.
Hyphens, underscores, etc. I always have to first think about which option I went with.
Some services don't even allow special characters so I have to separate the password with zeros (which is absolutely idiotic but hey haha)

If this is not something you guys want to consider then that's okay, I thought I'd ask though :D

**Comment by rafakob** [comment]
Sure, we can think about the toggle.

**Comment by Lordmau5** [comment]
Additionally, maybe an extra popup / check if the first or last character (or multiple characters before or after the first and last letter) of the password is a space?

I think that might be a good addition to this as well :)
