### ISSUE TITLE
Can't add Instagram

### ISSUE THREAD

**Issue by ncdaol** [twofas/2fas-android#110]
In the last step of adding 2FA, verifying by entering the TOTP, Instagram says the TOTP isn't correct. 
![image](https://github.com/twofas/2fas-android/assets/37809874/b3894626-2767-4399-9bb2-725d27ebe31c)

**Comment by partha51613** [comment]
Instagram is working fine for me. 
Most probably your **mobile/pc** time settings are **not in sync** / **are in different timezones**.

![image](https://github.com/twofas/2fas-android/assets/23007104/da040b11-650c-4610-a51f-4eaf661e3414)

**Comment by ncdaol** [comment]
> Instagram is working fine for me. Most probably your **mobile/pc** time settings are **not in sync** / **are in different timezones**.
> 
> ![image](https://private-user-images.githubusercontent.com/23007104/305343870-da040b11-650c-4610-a51f-4eaf661e3414.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwNzExODgsIm5iZiI6MTcwODA3MDg4OCwicGF0aCI6Ii8yMzAwNzEwNC8zMDUzNDM4NzAtZGEwNDBiMTEtNjUwYy00NjEwLWE1MWYtNGVhZjY2MWUzNDE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE2VDA4MDgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxOGJkMTMyYWNjN2RiZWExOWZkN2YzNmViYmQ2OGE2NjVmNTZiYTI5MGU1NGJlNmFmMmE5MGEyNzI1YjdjNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8GjpfDEgP90zWO1mJh9tM68tWQh8FHa-RVf36hythrE)

I spent all day moving from Authy to 2FAS and only Instagram was throwing up errors, so it probably wasn't that.

It works now tho. Might have been something on Metas side.

**Comment by ncdaol** [comment]
Closing
