### ISSUE TITLE
backup format info

### ISSUE THREAD

**Issue by paolostivanin** [twofas/2fas-android#117]
Hello,
I'd like to implement importing/exporting 2fas backups into my application. Where can I find information about the backup format (encryption details, json format details, etc)? 
Thanks

**Comment by Spacellary** [comment]
@paolostivanin Heya! Until we get a response from the 2FAS team...

Taking a look at another open source application that already supports 2FAS imports, their importers are here:

https://github.com/beemdevelopment/Aegis/tree/master/app/src/main/java/com/beemdevelopment/aegis/importers

Perhaps that can help.

**Comment by paolostivanin** [comment]
Thanks a lot, that for sure helps :) I'll dig into the code for now.

**Comment by Spacellary** [comment]
@paolostivanin Might sound weird but from what I've seen you only likely to get an input from the 2FAS team on this on their Discord.

**Comment by elliotwutingfeng** [comment]
It appears the same salt is used for both `servicesEncrypted` and `reference`, but they use different `iv`.

**Comment by paolostivanin** [comment]
hello!
Nope, I'm using the same salt and iv for both `servicesEncrypted` and `reference`. Should they be different instead?

thx

**Comment by elliotwutingfeng** [comment]
I tried exporting my own vault from the android app, and got different `iv`, but same `salt`.

Though for decryption it doesn't matter since decryption can be done without `reference`, but the app appears to perform an additional check to see if encryptedReference can be decrypted with the given key, salt and iv.

**Comment by paolostivanin** [comment]
Interesting. Good catch, I'll dig into it then

**Comment by paolostivanin** [comment]
Nope, using a different iv didn't help. They must be using a different key from the user provided one then.

**Comment by elliotwutingfeng** [comment]
It seems like the having any `iv` works too. I modified my existing Ruby decryptor to make encrypted backups. Imports to the Android app seem to work. Under the `encrypt` branch: <https://github.com/elliotwutingfeng/2fas-backup-decryptor/tree/encrypt>.

Try echoing the output of this to a file.

```ruby
load 'lib/decrypt.rb'

plain_text = File.read('test/plaintext_test.json', :encoding => 'utf-8')
password = 'example.com'
salt = Base64.strict_encode64 OpenSSL::Random.random_bytes 16
iv = Base64.strict_encode64 OpenSSL::Random.random_bytes 12
encrypted_vault = encrypt_vault(plain_text, password, salt, iv)
puts encrypted_vault
```

**Comment by paolostivanin** [comment]
@elliotwutingfeng :thinking: salt should be `256` bytes and not `16`: https://github.com/twofas/2fas-android/blob/cea1e7277e30bccb51591b7b22ac4ca8be3c4b08/core/cipher/src/main/java/com/twofasapp/cipher/backup/internal/BackupSaltGeneratorRandom.kt#L9

**Comment by paolostivanin** [comment]
thanks a lot @elliotwutingfeng , I fixed it :smile: could have never done without your help!
Basically, I was missing the tag on the reference :man_facepalming:

**Comment by elliotwutingfeng** [comment]
Under AES-GCM, the same **iv** should not be reused for both `servicesEncrypted` and `reference` because they use the same **key** and **salt**, and the plaintext of reference is public information. See <https://crypto.stackexchange.com/a/68525>

**Comment by marcopaganini** [comment]
This is a useful thread. I'm also interested in this for one of my pet projects (http://github.com/marcopaganini/termotp). @elliotwutingfeng is there some official documentation or should we follow the steps of @paolostivanin ?

**Comment by elliotwutingfeng** [comment]
I don't see any documentation about this in 2FAS, but the encryption and decryption steps can be deduced from the source code.
