### ISSUE TITLE
Ability to set/reset known brand logos (not add a custom one)

### ISSUE THREAD

**Issue by bbceg** [twofas/2fas-android#118]
I've just migrated to 2FAS from Authy and some of the logos are showing correctly but many are not. If I disable 2FA and re-add the website the logo appears. Is there any way to force a logo "lookup" for an existing entry?

**Comment by Tipoff4317** [comment]
Yeah, this would be nice also for the sites that have their icons added after you have already put in your entries.  

This is more like a feature request.

**Comment by KobeW50** [comment]
This is already possible. Hold down on token you want to change the logo for in the 2FAS app. 

Press Edit. Then select the 2FAS icon under personalization, and then the option to Change the icon will appear just below the logo

**Comment by bbceg** [comment]
Thanks @KobeW50 , slightly embarrassed I missed that one!
