### ISSUE TITLE
Browser request doesn't save my choice

### ISSUE THREAD

**Issue by patrik-martinko** [twofas/2fas-android#125]
When I send a request from the browser, the app doesn't remember my choice for the domain even though I click to "Save my choice". It always shows me the "select the service to authorize and save with this domain" screen when I click on the notification sent from the browser.

I tested it with 2FAS test token (https://2fas.com/check-be).

**Comment by patrik-martinko** [comment]
OK. I found out that the screen with choices shows only when I click on the notification sent from the browser. When I open the app manually and ignore the notification, the popup with remembered domain and the "Approve" button appears.

Not the best UX, but it works.

**Comment by jamime** [comment]
Same issue here - this should be re-opened.
