### ISSUE TITLE
Feature request: Integrate autofill for 2FAS

### ISSUE THREAD

**Issue by eennoo** [twofas/2fas-android#15]
It would be nice if 2FAS used the autofill integration on Android, especially for keyboards (that supports it).

The use case being that a user would get the 2FAS prompt in the keyboard when the 2FAS application identifies that the user is in an app or on a website which the user has a 2FA account set up for in the 2FAS application. Clicking on this would ask the user to authenticate themself with their authentication method (PIN, Fingerprint) and then the token would automatically be filled out in the code input field on the website or in the app the user is currently in. See how other password managers solved this, such as Bitwarden etc. 

https://developer.android.com/guide/topics/text/ime-autofill

I do apologize if this has been requested before, or if it's already on the roadmap as a planned feature.
It may also be that 2FA tokens work differently than password managers when it comes to the autofill integration on Android, so I am not sure about the feasibility of this feature request.   

Thanks. :)

**Comment by eennoo** [comment]
Thanks for the quick reply. 

I'll request it from Google then. :) 

I found this issue https://issuetracker.google.com/issues/270545497 in case anyone's interested and wants to +1 it.

**Comment by rafakob** [comment]
I'll monitor the ticket. If Google decides to add it at some point, we will definitely implement autofill ASAP.
