### ISSUE TITLE
feat: Can we organize the code into folders? example work, personal and etc.

### ISSUE THREAD

**Issue by mariojgt** [twofas/2fas-android#155]
### Feature description

Create a new folder for my personal and work so i can better organize my codes.

### Motivation

It helps to organize my authentication codes. 

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by KobeW50** [comment]
In the search bar of the home tab tap the 3-dot icon. Then press "Manage list". From there you can add codes to folders.

**Comment by mariojgt** [comment]
Thank you so much 🤟
