### ISSUE TITLE
feat: Google Drive alternative options

### ISSUE THREAD

**Issue by LanceLake** [twofas/2fas-android#167]
### Feature description

For those who don't want google drive to be the place to store backup files, allow for some other options to place an encrypted file in the directory so you can store it where you want.

### Motivation

Because there is no guarantee that google won't take someone's drive access. 

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by s3rious0** [comment]
Hey @LanceLake,

this is an duplicate of #74. 

I think you can close this Issue and comment on the other Issue.

Thank you. 

Greeting.

**Comment by LanceLake** [comment]
Thank you. I didn't see that there.
