### ISSUE TITLE
Doesn't ask notification permission

### ISSUE THREAD

**Issue by tropics1999** [twofas/2fas-android#2]
Hi,

I just installed the app and it works great, except when I synced with the browser extension it was not sending push notifications. After a bit of digging notification permissions for the app were set to off in my phones settings (Pixel 5 on Android 13). I believe the app should have asked for permissions when I tried to set up the browser extension.

Please feel free to correct me if I am incorrect, I have not tried to replicate it.

Thanks!

**Comment by 2fas-com** [comment]
Yup, you're right! We've already implemented additional info during the pairing process! It will be available with the next update! Thank you!
