### ISSUE TITLE
An Option to mask 2FA Codes with Dots on Home Screen and long press Popup Window for Maximum Security

### ISSUE THREAD

**Issue by matt873** [twofas/2fas-android#21]

**Comment by 2fas-com** [comment]
We'll talk about it and probably introduce it because it is a very good idea. Thanks!

**Comment by mhmatthewhugley** [comment]
> We'll talk about it and probably introduce it because it is a very good idea. Thanks!

This missing feature prevents me from switching away from Aegis.

**Comment by 2fas-com** [comment]
The option to mask codes with dots has been added.
