### ISSUE TITLE
Tokens aren't visible anymore after latest update

### ISSUE THREAD

**Issue by IRONB0SS** [twofas/2fas-android#22]
![20230501_174820.jpg](https://user-images.githubusercontent.com/97769328/235465910-b088e9ec-9a72-4c7c-a1c1-1285a2fbf248.jpg)

Samsung Galaxy S7
Android 7.00

![Screenshot_20230501-175650_2FAS Auth.jpg](https://user-images.githubusercontent.com/97769328/235467217-800afe0a-5888-472a-b4f2-034649615926.jpg)

**Comment by IRONB0SS** [comment]
> Is list visible in that mode?

Hey, I tried and no luck

**Comment by rafakob** [comment]
@IRONB0SS I found the bug. Fix is already uploaded to Google Play (app version 4.5.5). It should be available to you in couple of hours.

As a temporary fix you can add a new group to your list. Go to "Manage list" and hit "Add group" button in top right corner. This should reveal the default "My tokens" group.
