### ISSUE TITLE
Authy

### ISSUE THREAD

**Issue by PeterKW** [twofas/2fas-android#24]
Is there a way to import from authy at all?

**Comment by 2fas-com** [comment]
Unfortunately, there is no simple way to import tokens from Authy because they don't allow it and basically lock you in. There is however a complicated/dev way to import things. Here is the video with a tutorial: https://youtu.be/n7ruB_uFcj4

**Comment by FredHappyface** [comment]
Might be useful to pin this or add an faq item

Follow the guide at https://gist.github.com/gboudreau/94bb0c11a6209c82418d01a59d958c93

Use the second block: "save your tokens as a JSON file to import into Bitwarden". Note I've had to use Aegis to do a transform here, less than ideal!
