### ISSUE TITLE
blank screen preview missed

### ISSUE THREAD

**Issue by PsyCrow-code** [twofas/2fas-android#25]
with the last update, the app preview when pressed the recent app button on the navigation bar, in the past the app preview was empty screen, now after update, the app preview is not blank, that is a security hole, I liked the previous behavior

**Comment by rafakob** [comment]
Thanks for reporting that, good catch. I will fix it immediately.

**Comment by rafakob** [comment]
Fix is deployed in version 4.5.6, should be available in store in couple of hours.
