### ISSUE TITLE
App Crashes

### ISSUE THREAD

**Issue by chute8427** [twofas/2fas-android#29]
I am a user of your 2fa app and I have been experiencing some issues with the browser extension QR code scanning.  Whenever I try to scan the QR code, the app crashes abruptly.  I would like to report this bug and seek your assistance.

I am using a Huawei Nova 5z mobile phone with the HarmonyOS 3.0.0.165 operating system.  Would it be possible for you to investigate this issue and provide a fix for it?

Thank you for your attention to this matter.

**Comment by 2fas-com** [comment]
How did you install our app (since Huaweis don't have access to Google Play Store), and which version of the app do you have?

**Comment by chute8427** [comment]
I installed 2fas via APKPure, version 4.5.10.

**Comment by rafakob** [comment]
We do not officially support Huawei devices. We will be looking into other publishing channels but right now Huawei is not supported. Closing for now.
