### ISSUE TITLE
Help me get my data back

### ISSUE THREAD

**Issue by Artem13327** [twofas/2fas-android#30]
I made a backup of the data using a third-party application and then restored the application through it, but for some reason, for some reason, after the restoration, the application crashes

**Comment by 2fas-com** [comment]
That's because third-party applications don't have access to the codes and will get blocked, that's why it's crashing.

**Comment by 2fas-com** [comment]
Did you use the iCloud/Google Drive backup before uninstalling the app?

**Comment by geekyouth** [comment]
https://github.com/twofas/2fas-android/issues/62

I have also encountered the issue of recovery.
