### ISSUE TITLE
Please add support for Steam Guard codes.

### ISSUE THREAD

**Issue by rafaelrandom** [twofas/2fas-android#34]
Some otp apps support Steam Guard codes, I would like 2FAs to support Steam Guard as well.

**Comment by 2fas-com** [comment]
We're planning to work on it, but right now we have a lot of other priorities. And that's precisely why we are open source so that our community can help us with such things and requests.

**Comment by Schluggi** [comment]
I just want to switch from andOTP since there is an import option now. But I want all my codes in one app so I have wait until Steam Guard is supported 😢

I think the issue should be open, since there is no support yet.

**Comment by rafakob** [comment]
@Schluggi Steam support is already completed, it just require some testing on our side. It should be released in upcoming 1-2 weeks. Stay tuned for version `5.1.0`. ✌️

**Comment by Schluggi** [comment]
@rafakob, thanks for the update! Great news :)

**Comment by rafakob** [comment]
@Schluggi 5.1.0 is out. I'm doing staged rollout in Google Play, so it should be available too all users in couple of days.
https://github.com/twofas/2fas-android/releases/tag/5.1.0

**Comment by Schluggi** [comment]
@rafakob Thank you!

**Comment by 2fas-com** [comment]
https://2fas.com/support/2fas-mobile-app/how-to-add-a-steam-guard-token/
