### ISSUE TITLE
Official APK on Releases

### ISSUE THREAD

**Issue by DarkLordGMS** [twofas/2fas-android#38]
Good morning,

Would it be possible to add the official full APK (with all the required dependencies/libraries) on the "releases" section?
https://github.com/twofas/2fas-android/releases

The APK is not available on the official website either even though README.md file found here https://github.com/twofas/2fas-android#getting-started makes it look like you can download the APK.

Some of us would like to use 2FAS but we don't have access to download it through the Google Play Store.
Having the official full APK with all the required dependencies/libraries on the "releases" section would allow us to sideload the app on non Google Android devices like Amazon Tablets (since the 2FAS app it's not available on the Amazon AppStore).
It would be really useful.

Thanks in advance.

**Comment by 2fas-com** [comment]
We aren't planning to do that now, but we'll think about it and see in the future.

**Comment by DarkLordGMS** [comment]
> We aren't planning to do that now, but we'll think about it and see in the future.

Seriously? You can't do something as simple as providing the APK of the app? This project is a joke.
Thanks for helping me realize this before it was too late!

**Comment by NextGenOP** [comment]
Consider using github actions to release apk file to Github Release

**Comment by 2fas-com** [comment]
After some talks, we've decided to add APK here on GitHub. Stay tuned!

**Comment by amxsa** [comment]
> After some talks, we've decided to add APK here on GitHub. Stay tuned!

Look forward to

**Comment by DarkLordGMS** [comment]
> > After some talks, we've decided to add APK here on GitHub. Stay tuned!
> 
> expectative

Don't hold your breath. These people are joke. So irresponsible.  
They promised this over 3 months ago and not even once have they added the APK. 

These are the kind of people you expect that have a secure app? 
If they're lazy and irresponsible in such a simple thing, how would you expect them to be responsible with vulnerabilities and other major issues?

Just switch to something else like I did.

**Comment by 2fas-com** [comment]
We understand your disappointment. However, please keep in mind that we are a relatively small but dedicated team creating a free app, funded by user donations. We are working conscientiously to implement all the excellent suggestions from our users while also prioritizing the security and privacy of our app. Regarding the APK, we confirmed yesterday that our QA team will now test it, and it will be available after the next update. Sorry, you had to wait so long...

**Comment by xerta555** [comment]
> We understand your disappointment. However, please keep in mind that we are a relatively small but dedicated team creating a free app, funded by user donations. We are working conscientiously to implement all the excellent suggestions from our users while also prioritizing the security and privacy of our app. Regarding the APK, we confirmed yesterday that our QA team will now test it, and it will be available after the next update. Sorry, you had to wait so long...

Better late than never

**Comment by Ashvith10** [comment]
@2fas-com I've never done this before, but I could give this a try.

**Comment by rafaelazvdo** [comment]
> > We aren't planning to do that now, but we'll think about it and see in the future.
> 
> Seriously? You can't do something as simple as providing the APK of the app to improve adoption? You literally just have to upload the APK to GitHub or post it on your website after uploading it to Google Play Store. It takes less than a minute. This project is a joke. Thanks for helping me realize this before it was too late.
> 
> Good luck.

The official apk was released on github, you can now close the issue.

**Comment by denji** [comment]
Need reproducible release in .apk format on the official website, because HUAWEI AppGallery is not available.
