### ISSUE TITLE
Feature Request: Support for WebDAV

### ISSUE THREAD

**Issue by xezzon** [twofas/2fas-android#39]
I prefer to backup my tokens with WebDAV. Can it be supported?

**Comment by 2fas-com** [comment]
Right now, we're planning to introduce cloud snapshots as a new backup method. If we were to also introduce a WebDAV method, it won't be in the nearest update. So we'll keep you posted on whether we'll start working on it.

**Comment by KobeW50** [comment]
Closing in favor of https://github.com/twofas/2fas-android/issues/74
