### ISSUE TITLE
Support for automated backup

### ISSUE THREAD

**Issue by prodigy7** [twofas/2fas-android#4]
I am currently still using AndOTP. There is an option there to automatically create a backup file whenever changes are made. I use this to automatically store a backup on my NAS. Could you implement something similar?
It would be good if you could encrypt the backup with a password, then it can also be stored locally on the smartphone, where it is then saved.

**Comment by 2fas-com** [comment]
Yes, we're currently planning a snapshots feature.

**Comment by dimaguy** [comment]
Hey there @2fas-com, it's been almost a year since you've said there was a plan for snapshots, is there any update on that front?
