### ISSUE TITLE
Feature: Add bitwarden import support 

### ISSUE THREAD

**Issue by FredHappyface** [twofas/2fas-android#42]
## Background 

The guide at https://gist.github.com/gboudreau/94bb0c11a6209c82418d01a59d958c93 provides a handy block of js to spit out a json file perfect for importing into bitwarden/ or competitors like Aegis 

## Feature 

Please add this functionality to 2fas to improve migration from competitor products 

Thanks :)

**Comment by 2fas-com** [comment]
The link that you gave us contains a script that generates QR codes from Authy. And these work correctly in our app.

**Comment by 2fas-com** [comment]
Can we help with something else around this issue? If you have any questions, please ask!

**Comment by FredHappyface** [comment]
The QR codes did not seem to behave in my case. Each item generated two qr codes and the incorrect issuer is identified.

**Comment by 2fas-com** [comment]
In that case, you should ask the "Export TOTP tokens from Authy" authors - it looks like a bug in their script. Our QR scanner works correctly (we've just double-checked it) - you can also check by scanning an example QR shown in  [AuthyToOtherAuthenticator.md](https://gist.github.com/gboudreau/94bb0c11a6209c82418d01a59d958c93).

**Comment by FredHappyface** [comment]
Oh awesome stuff, thanks for getting back to me on that ☺️
