### ISSUE TITLE
Feature: Show/ or Search by Issuer

### ISSUE THREAD

**Issue by FredHappyface** [twofas/2fas-android#43]
## Background 

Many other 2fa products show the issuer in text in some way.

| Product | Issuer |
| --- | --- |
| Aegis | issuer (username) |
| Authy | issuer: username |

However, 2fas does not despite storing the info

Also it isn't possible to search by issuer. For example I might search for "Bitwarden", however I'm not likely to search for my log in email as I use this for many services

## Feature 

Please add the option to show the issuer in some way, or search by issuer 

Thanks :)

**Comment by 2fas-com** [comment]
Thank you very much for the suggestion. We'll talk about it internally and consider adding it in future updates!

**Comment by 2fas-com** [comment]
Searching by Issuer has been added.
