### ISSUE TITLE
Crash when pairing with 4.6.0

### ISSUE THREAD

**Issue by jcreigh** [twofas/2fas-android#45]
With 4.6.0 I can no longer pair new services. Clicking the button simply causes the app to crash. I downgraded and verified that 4.5.14 works fine.

I sent a crash report using android and here is a screenshot of it
![image](https://github.com/twofas/2fas-android/assets/5660214/f4bed0c9-5460-486c-ab98-4bf8da4184eb)

**Comment by rafakob** [comment]
Thank you for your report! I will take a look at this right away.

**Comment by rafakob** [comment]
We've released version 4.6.1 which should fix the issue (it was very specific bug for Android 8). Release should be available to you in next 24 hours, let me know if it works.

**Comment by jcreigh** [comment]
Yep, works now :) Thanks for the quick fix.
