### ISSUE TITLE
Add donate link to the repository

### ISSUE THREAD

**Issue by Panquesito7** [twofas/2fas-android#46]
The other repositories seem to have the sponsor button, however, this one does not have it.
It'd be great if it could be added, so that it has more promotion as well. 🙂

**Comment by 2fas-com** [comment]
It is now added! So, thank you for the suggestion 😁

**Comment by Panquesito7** [comment]
Thanks. I see that there's a sponsor profile on the organization. You can create a [community health file](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file) to easily add a sponsor button to all the repositories, as well as a code of conduct and other files. Let me know if you need any help with that. 🙂
