### ISSUE TITLE
(feature request) Confirm PIN without tapping OK

### ISSUE THREAD

**Issue by zeoint** [twofas/2fas-android#49]
Please provide a round checkbox option in **Security -> PIN code** to ' Confirm PIN without tapping OK '.

It should appear above or below the 'Please enter your new n-digit code PIN' dialogue when a PIN is being set or changed.

---
- If the round checkbox is selected, then the app pin display will be same as now.
- If the round checkbox is not selected, then the app pin display will have 'OK' button beside 0 (zero) on the right side.
- And will not unlock the phone directly, but 'OK' should be clicked.

**Comment by 2fas-com** [comment]
Thanks for the suggestion! We'll discuss this and let you know.

**Comment by 2fas-com** [comment]
We've saved this idea for the future because we're already planning to do a redesign of the logging process in the future, but we have eta right now. So once we get to it, we'll take your suggestion into consideration, because it is a good idea. Thanks!
