### ISSUE TITLE
Feature Request: full Material you support 

### ISSUE THREAD

**Issue by milindgoel15** [twofas/2fas-android#56]
I had suggested this feature a year back on discord but it seems forgotten. So creating a GitHub to keep a track on.

Since the app uses md3 elements, we would appreciate dynamic color theming based on the user's wallpaper as an optional switch toggle keeping the app's brand colors as default as discussed on discord.

**Comment by 2fas-com** [comment]
We're not planning to implement the Material you support as of this moment.
