### ISSUE TITLE
Improvements: some minor UI issues 

### ISSUE THREAD

**Issue by milindgoel15** [twofas/2fas-android#57]
1. Switch toggle appears cut

The biometric lock toggle in the security settings is cut from both sides due to lack of available space from leading items.

<img src="https://github.com/twofas/2fas-android/assets/45682747/04324fe4-5417-43b0-9acb-45253543d127" width="200" />

[Discord message link for this](https://discord.com/channels/880495121525796914/903153325007048735/1110593966128238652)

2. Different animation

In the settings tab, the setting "2fas backup" has different opening animation than the rest.

**Comment by 2fas-com** [comment]
Thanks for bringing this to our attention. We'll get on to fixing it.

**Comment by 2fas-com** [comment]
Fixed.
