### ISSUE TITLE
Bug Report: Cannot connect with browser extensions and Website name display error

### ISSUE THREAD

**Issue by magojohnji** [twofas/2fas-android#60]
Hello,

When I am using the 2FAS app, I've found a few bugs that aren't serious, but affect the experience of using it
1. Connecting with browser extensions error: It flashes back after a circle on the screen.
2. Website name display error: The website name seems depend on the email address for website registration. For example, Discord shows up as my outlook email, and Google account is displayed as a mail, not a Google logo, but Facebook and Ins display well.
---
My phone configuration is:
MIUI14 (Android 13)
The 2FAS app is installed by downloading the apk file from apkpure.

**Comment by magojohnji** [comment]
Need I give some logs? I haven't noticed where the logs are.

**Comment by 2fas-com** [comment]
Hi there, thanks for sharing this. We're already fixing the second problem you mentioned, so it should be fixed in future updates. As for the first problem, could you send us a screenshot, or preferably a short movie of this happening, so that we could see it? And, of course, provide as much information as you can from your end.

**Comment by magojohnji** [comment]
> Hi there, thanks for sharing this. We're already fixing the second problem you mentioned, so it should be fixed in future updates. As for the first problem, could you send us a screenshot, or preferably a short movie of this happening, so that we could see it? And, of course, provide as much information as you can from your end. 

I'm very sorry I changed my phone, so I can't reproduce the first problem I mentioned. 
But I can say what I see: I scan the QR code displayed by the browser plugin, then there's a display on the screen (which I take to mean that it's connecting), and then about 3 seconds after that, the program flashes back and returns to the desktop.
