### ISSUE TITLE
Backslash not allowed in backup password

### ISSUE THREAD

**Issue by ArkadiuszNiemiec** [twofas/2fas-android#63]
Is there a reason for not allowing the backslash in a backup encryption password?
It bothers me as it's often found in my passwords.

Thanks

**Comment by elliotwutingfeng** [comment]
> Is there a reason for not allowing the backslash in a backup encryption password?
> It bothers me as it's often found in my passwords.
> 
> Thanks

Seems to be working on Android now.

**Comment by KobeW50** [comment]
Tested and this issue appears to be fixed.
