### ISSUE TITLE
Cannot receive notification from browser extension

### ISSUE THREAD

**Issue by andya1lan** [twofas/2fas-android#7]
Hi Team,
I am new to this OTP app which has a very nice UI. I tried but cannot receive notifications from browser extension on my Android.
Steps:

1. Go to a page with OTP login on browser and press Ctrl+Shift+2
2. I can see a pop-up from extension but didn't receive on my phone.
3. I tried turning on the app / switching to notifications section and triggered Ctrl+Shift+2 again but still no notifications received.

Plz help me if I have something wrong or tell me how to troubleshoot(eg, what logs are needed)
Much thx for developing the app!

**Comment by 2fas-com** [comment]
Please update our app and enable push notifications in system settings. If the problem persists please respond here.
