### ISSUE TITLE
2fas-android scan Browser Extension QR code flash crash

### ISSUE THREAD

**Issue by amxsa** [twofas/2fas-android#71]
2fas-android scan Browser Extension QR code flash crash

The twofas_c:// protocol does not appear to be supported ？
-------------------------------------------
Open the 2FAS mobile app
Go to Settings → Browser Extension
Tap "Pair with web browser" and scan the QR code

**Comment by Cris--** [comment]
Crashes here also after scan, crash report was sent (hope so!).

**Comment by KobeW50** [comment]
Hi there. Does this issue still occur? If yes,nplease provide specific instructions to reproduce the issue, including the service(s) that this issue occurs with. Thanks!

**Comment by Cris--** [comment]
Reflashed a newer custom rom (A14) and QR scan has working.
