### ISSUE TITLE
"Pair with web browser" results in the app crashing in newly installed app (no data)

### ISSUE THREAD

**Issue by Tipoff4317** [twofas/2fas-android#79]
# Description
"Pair with web browser" results in the app crashing for a newly installed app.  This can be duplicated 100% on my end.

# Duplication Steps
1) Install app
2) [not required] For me, to show you the screen shot, set the app up to allow screen shot
3) Attempt to "Pair with web browser"

App crashed.

Doesn't matter if I clear the cache and the data and start over.  Doesn't matter if I remove and reinstall the extension.  Doesn't matter if the extension is set to work in private windows or not.

This has worked for me before.

# Setup
1) Android 13
2) App version 4.7.0
3) Windows 11 Pro
3) Firefox 115.3.1esr (64 bit)
4) Browser extension version 1.4.5

# Screenshot

https://github.com/twofas/2fas-android/assets/17734927/a0bb7610-5a14-4626-afb8-441247c1e0cc

**Comment by rafakob** [comment]
Hey, thanks for your report. We know about that issue and it will be fixed in upcoming release.

**Comment by Tipoff4317** [comment]
OK, with the app version 5.0.0 and FF browser extension 1.4.5, this issue was resolve for me.
