### ISSUE TITLE
Add icon for eBay

### ISSUE THREAD

**Issue by dftf-stu** [twofas/2fas-android#89]
eBay [has-recently](https://community.ebay.co.uk/t5/Announcements/A-more-secure-way-to-access-your-account-is-here/ba-p/7513704) added-support for using 2FA apps (whereas previously they only-offered SMS-based 2FA, or having the official eBay app installed on your phone, and receiving sign-in approval-alerts in there).

I've just changed-over to the app-based option, by scanning the QR code in the 2FAS Android app, but I notice there is no icon for the eBay service, and I just see an orange-brown circle with "EB" in the middle to the left of its entry in the codes list.

Could an icon for eBay be added in a future-update please (perhaps you could use the basket favicon they use on their website)?

Thanks

**Comment by 2fas-com** [comment]
Thanks. The icon has been added.

**Comment by dftf-stu** [comment]
@2fas-com: when will this change go-live in the Android app?

I'm currently running the latest one available via the Play Store (v5.3.5 dated 14 Feb 2024) and yet I still don't see the icon for eBay, and my only options are the red 2fas shield-icon, or creating my own custom icon by picking a colour, then two letters.

I assume I don't have to turn-off 2FA on eBay, then re-repair surely?  Once the icon is added I'd expect it to then just appear beside that service, as I'd imagine most users would.

Can you confirm?

Thanks
