### ISSUE TITLE
Deleting doesn't work

### ISSUE THREAD

**Issue by K0-RR** [twofas/2fas-android#91]
I can't delete a token from the list. It disappears and then comes back after a second.
v5.1.0

**Comment by RDKRACZ** [comment]
Interesting discovery - I can't delete ONLY ONE SPECIFIC token. Deleting any other token works fine.

**Comment by RDKRACZ** [comment]
It does not appear in the trash either.

Ohh. I tried editing the token name and it changed successfully. Then I deleted it again and after it reappeared like previously **it also reverted the name change**. @rafakob Are there any logs I can access within the app itself?

**Comment by 2fas-com** [comment]
Does the problem still occur? If so, can you check what happens when you temporarily turn off synchronization with Google Drive and see if the problem then appears?

**Comment by K0-RR** [comment]
> Does the problem still occur?

No
