### ISSUE TITLE
(Feature request) 2FAS as Password Safe

### ISSUE THREAD

**Issue by Spider19996** [twofas/2fas-android#94]
Hey, how about a function that allows you to use 2FAS as a password manager? Also services that do not yet offer 2FA could be saved in the app.

Best wishes,
Robin

**Comment by xerta555** [comment]
> Hey, how about a function that allows you to use 2FAS as a password manager? Also services that do not yet offer 2FA could be saved in the app.
> 
> Best wishes,
> Robin

This idea isn't bad, but this would mean having to create a new extension for web browsers or modify the existing one, in addition to the effort required to adapt the application for this type of use.

**Comment by KobeW50** [comment]
This video on the 2fas YT channel explains why this should not be done.

https://youtu.be/PS632zXpsMc
