### ISSUE TITLE
Unable to activate biometric lock on Asus Zenfone 10

### ISSUE THREAD

**Issue by illuzor** [twofas/2fas-android#97]
Nothing happens on click.

Asus Zenfone 10:

https://github.com/twofas/2fas-android/assets/1530314/0c989f8a-32ee-43dd-a5a0-5bce4222ea0b

Google Pixel 6:

https://github.com/twofas/2fas-android/assets/1530314/5857e5b7-35eb-47b3-8118-6412b85d8be2

**Comment by rafakob** [comment]
Thank you for the videos!

We're looking into that issue right now. I do have a couple of follow-up questions:

1) Do you have any fingerprints enrolled in system on the Asus device?

2) Have you done any actions before on the Asus, like changing or removing PIN, changing something in system lock screen settings? Or was it just simple: Install app from store -> Setup PIN -> Setup Biometrics?

3) Have you tried to reinstall the app? (make sure to backup your codes before!)

**Comment by illuzor** [comment]
1. Yes. No problem with another apps
2. Not sure, but maybe
3. No. I will try to reinstall now

**Comment by illuzor** [comment]
@rafakob it works after reinstall. Thank you!

**Comment by rafakob** [comment]
I've made a small change on that screen which should resolve any future issues like that.
